<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Ingest.Core\Ingest.Core.csproj" />
    <ProjectReference Include="..\Ingest.Application\Ingest.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="InfluxDB.Client" Version="5.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
