// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stream/frame.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Chirpstack.Stream {

  /// <summary>Holder for reflection information generated from stream/frame.proto</summary>
  public static partial class FrameReflection {

    #region Descriptor
    /// <summary>File descriptor for stream/frame.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FrameReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJzdHJlYW0vZnJhbWUucHJvdG8SBnN0cmVhbRofZ29vZ2xlL3Byb3RvYnVm",
            "L3RpbWVzdGFtcC5wcm90bxoTY29tbW9uL2NvbW1vbi5wcm90bxoLZ3cvZ3cu",
            "cHJvdG8ikAIKDlVwbGlua0ZyYW1lTG9nEhMKC3BoeV9wYXlsb2FkGAEgASgM",
            "EiEKB3R4X2luZm8YAiABKAsyEC5ndy5VcGxpbmtUeEluZm8SIQoHcnhfaW5m",
            "bxgDIAMoCzIQLmd3LlVwbGlua1J4SW5mbxIdCgZmX3R5cGUYBCABKA4yDS5j",
            "b21tb24uRlR5cGUSEAoIZGV2X2FkZHIYBSABKAkSDwoHZGV2X2V1aRgGIAEo",
            "CRIoCgR0aW1lGAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIY",
            "ChBwbGFpbnRleHRfZl9vcHRzGAggASgIEh0KFXBsYWludGV4dF9mcm1fcGF5",
            "bG9hZBgJIAEoCCKaAgoQRG93bmxpbmtGcmFtZUxvZxIoCgR0aW1lGAEgASgL",
            "MhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBITCgtwaHlfcGF5bG9hZBgC",
            "IAEoDBIjCgd0eF9pbmZvGAMgASgLMhIuZ3cuRG93bmxpbmtUeEluZm8SEwoL",
            "ZG93bmxpbmtfaWQYBCABKA0SEgoKZ2F0ZXdheV9pZBgFIAEoCRIdCgZmX3R5",
            "cGUYBiABKA4yDS5jb21tb24uRlR5cGUSEAoIZGV2X2FkZHIYByABKAkSDwoH",
            "ZGV2X2V1aRgIIAEoCRIYChBwbGFpbnRleHRfZl9vcHRzGAkgASgIEh0KFXBs",
            "YWludGV4dF9mcm1fcGF5bG9hZBgKIAEoCEKjAQoYaW8uY2hpcnBzdGFjay5h",
            "cGkuc3RyZWFtQgpGcmFtZVByb3RvUAFaMWdpdGh1Yi5jb20vY2hpcnBzdGFj",
            "ay9jaGlycHN0YWNrL2FwaS9nby92NC9zdHJlYW2qAhFDaGlycHN0YWNrLlN0",
            "cmVhbcoCEUNoaXJwc3RhY2tcU3RyZWFt4gIdR1BCTWV0YWRhdGFcQ2hpcnBz",
            "dGFja1xTdHJlYW1iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Chirpstack.Common.CommonReflection.Descriptor, global::Chirpstack.Gateway.GwReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Chirpstack.Stream.UplinkFrameLog), global::Chirpstack.Stream.UplinkFrameLog.Parser, new[]{ "PhyPayload", "TxInfo", "RxInfo", "FType", "DevAddr", "DevEui", "Time", "PlaintextFOpts", "PlaintextFrmPayload" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chirpstack.Stream.DownlinkFrameLog), global::Chirpstack.Stream.DownlinkFrameLog.Parser, new[]{ "Time", "PhyPayload", "TxInfo", "DownlinkId", "GatewayId", "FType", "DevAddr", "DevEui", "PlaintextFOpts", "PlaintextFrmPayload" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UplinkFrameLog : pb::IMessage<UplinkFrameLog>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UplinkFrameLog> _parser = new pb::MessageParser<UplinkFrameLog>(() => new UplinkFrameLog());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UplinkFrameLog> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chirpstack.Stream.FrameReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UplinkFrameLog() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UplinkFrameLog(UplinkFrameLog other) : this() {
      phyPayload_ = other.phyPayload_;
      txInfo_ = other.txInfo_ != null ? other.txInfo_.Clone() : null;
      rxInfo_ = other.rxInfo_.Clone();
      fType_ = other.fType_;
      devAddr_ = other.devAddr_;
      devEui_ = other.devEui_;
      time_ = other.time_ != null ? other.time_.Clone() : null;
      plaintextFOpts_ = other.plaintextFOpts_;
      plaintextFrmPayload_ = other.plaintextFrmPayload_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UplinkFrameLog Clone() {
      return new UplinkFrameLog(this);
    }

    /// <summary>Field number for the "phy_payload" field.</summary>
    public const int PhyPayloadFieldNumber = 1;
    private pb::ByteString phyPayload_ = pb::ByteString.Empty;
    /// <summary>
    /// PHYPayload.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString PhyPayload {
      get { return phyPayload_; }
      set {
        phyPayload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tx_info" field.</summary>
    public const int TxInfoFieldNumber = 2;
    private global::Chirpstack.Gateway.UplinkTxInfo txInfo_;
    /// <summary>
    /// TX meta-data.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chirpstack.Gateway.UplinkTxInfo TxInfo {
      get { return txInfo_; }
      set {
        txInfo_ = value;
      }
    }

    /// <summary>Field number for the "rx_info" field.</summary>
    public const int RxInfoFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Chirpstack.Gateway.UplinkRxInfo> _repeated_rxInfo_codec
        = pb::FieldCodec.ForMessage(26, global::Chirpstack.Gateway.UplinkRxInfo.Parser);
    private readonly pbc::RepeatedField<global::Chirpstack.Gateway.UplinkRxInfo> rxInfo_ = new pbc::RepeatedField<global::Chirpstack.Gateway.UplinkRxInfo>();
    /// <summary>
    /// RX meta-data.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Chirpstack.Gateway.UplinkRxInfo> RxInfo {
      get { return rxInfo_; }
    }

    /// <summary>Field number for the "f_type" field.</summary>
    public const int FTypeFieldNumber = 4;
    private global::Chirpstack.Common.FType fType_ = global::Chirpstack.Common.FType.JoinRequest;
    /// <summary>
    /// Frame type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chirpstack.Common.FType FType {
      get { return fType_; }
      set {
        fType_ = value;
      }
    }

    /// <summary>Field number for the "dev_addr" field.</summary>
    public const int DevAddrFieldNumber = 5;
    private string devAddr_ = "";
    /// <summary>
    /// Device address (optional).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DevAddr {
      get { return devAddr_; }
      set {
        devAddr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dev_eui" field.</summary>
    public const int DevEuiFieldNumber = 6;
    private string devEui_ = "";
    /// <summary>
    /// Device EUI (optional).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DevEui {
      get { return devEui_; }
      set {
        devEui_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Timestamp time_;
    /// <summary>
    /// Time.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "plaintext_f_opts" field.</summary>
    public const int PlaintextFOptsFieldNumber = 8;
    private bool plaintextFOpts_;
    /// <summary>
    /// Plaintext f_opts mac-commands.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool PlaintextFOpts {
      get { return plaintextFOpts_; }
      set {
        plaintextFOpts_ = value;
      }
    }

    /// <summary>Field number for the "plaintext_frm_payload" field.</summary>
    public const int PlaintextFrmPayloadFieldNumber = 9;
    private bool plaintextFrmPayload_;
    /// <summary>
    /// Plaintext frm_payload.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool PlaintextFrmPayload {
      get { return plaintextFrmPayload_; }
      set {
        plaintextFrmPayload_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UplinkFrameLog);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UplinkFrameLog other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PhyPayload != other.PhyPayload) return false;
      if (!object.Equals(TxInfo, other.TxInfo)) return false;
      if(!rxInfo_.Equals(other.rxInfo_)) return false;
      if (FType != other.FType) return false;
      if (DevAddr != other.DevAddr) return false;
      if (DevEui != other.DevEui) return false;
      if (!object.Equals(Time, other.Time)) return false;
      if (PlaintextFOpts != other.PlaintextFOpts) return false;
      if (PlaintextFrmPayload != other.PlaintextFrmPayload) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PhyPayload.Length != 0) hash ^= PhyPayload.GetHashCode();
      if (txInfo_ != null) hash ^= TxInfo.GetHashCode();
      hash ^= rxInfo_.GetHashCode();
      if (FType != global::Chirpstack.Common.FType.JoinRequest) hash ^= FType.GetHashCode();
      if (DevAddr.Length != 0) hash ^= DevAddr.GetHashCode();
      if (DevEui.Length != 0) hash ^= DevEui.GetHashCode();
      if (time_ != null) hash ^= Time.GetHashCode();
      if (PlaintextFOpts != false) hash ^= PlaintextFOpts.GetHashCode();
      if (PlaintextFrmPayload != false) hash ^= PlaintextFrmPayload.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PhyPayload.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(PhyPayload);
      }
      if (txInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TxInfo);
      }
      rxInfo_.WriteTo(output, _repeated_rxInfo_codec);
      if (FType != global::Chirpstack.Common.FType.JoinRequest) {
        output.WriteRawTag(32);
        output.WriteEnum((int) FType);
      }
      if (DevAddr.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DevAddr);
      }
      if (DevEui.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(DevEui);
      }
      if (time_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Time);
      }
      if (PlaintextFOpts != false) {
        output.WriteRawTag(64);
        output.WriteBool(PlaintextFOpts);
      }
      if (PlaintextFrmPayload != false) {
        output.WriteRawTag(72);
        output.WriteBool(PlaintextFrmPayload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PhyPayload.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(PhyPayload);
      }
      if (txInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TxInfo);
      }
      rxInfo_.WriteTo(ref output, _repeated_rxInfo_codec);
      if (FType != global::Chirpstack.Common.FType.JoinRequest) {
        output.WriteRawTag(32);
        output.WriteEnum((int) FType);
      }
      if (DevAddr.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DevAddr);
      }
      if (DevEui.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(DevEui);
      }
      if (time_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Time);
      }
      if (PlaintextFOpts != false) {
        output.WriteRawTag(64);
        output.WriteBool(PlaintextFOpts);
      }
      if (PlaintextFrmPayload != false) {
        output.WriteRawTag(72);
        output.WriteBool(PlaintextFrmPayload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PhyPayload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(PhyPayload);
      }
      if (txInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TxInfo);
      }
      size += rxInfo_.CalculateSize(_repeated_rxInfo_codec);
      if (FType != global::Chirpstack.Common.FType.JoinRequest) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) FType);
      }
      if (DevAddr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DevAddr);
      }
      if (DevEui.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DevEui);
      }
      if (time_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Time);
      }
      if (PlaintextFOpts != false) {
        size += 1 + 1;
      }
      if (PlaintextFrmPayload != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UplinkFrameLog other) {
      if (other == null) {
        return;
      }
      if (other.PhyPayload.Length != 0) {
        PhyPayload = other.PhyPayload;
      }
      if (other.txInfo_ != null) {
        if (txInfo_ == null) {
          TxInfo = new global::Chirpstack.Gateway.UplinkTxInfo();
        }
        TxInfo.MergeFrom(other.TxInfo);
      }
      rxInfo_.Add(other.rxInfo_);
      if (other.FType != global::Chirpstack.Common.FType.JoinRequest) {
        FType = other.FType;
      }
      if (other.DevAddr.Length != 0) {
        DevAddr = other.DevAddr;
      }
      if (other.DevEui.Length != 0) {
        DevEui = other.DevEui;
      }
      if (other.time_ != null) {
        if (time_ == null) {
          Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Time.MergeFrom(other.Time);
      }
      if (other.PlaintextFOpts != false) {
        PlaintextFOpts = other.PlaintextFOpts;
      }
      if (other.PlaintextFrmPayload != false) {
        PlaintextFrmPayload = other.PlaintextFrmPayload;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PhyPayload = input.ReadBytes();
            break;
          }
          case 18: {
            if (txInfo_ == null) {
              TxInfo = new global::Chirpstack.Gateway.UplinkTxInfo();
            }
            input.ReadMessage(TxInfo);
            break;
          }
          case 26: {
            rxInfo_.AddEntriesFrom(input, _repeated_rxInfo_codec);
            break;
          }
          case 32: {
            FType = (global::Chirpstack.Common.FType) input.ReadEnum();
            break;
          }
          case 42: {
            DevAddr = input.ReadString();
            break;
          }
          case 50: {
            DevEui = input.ReadString();
            break;
          }
          case 58: {
            if (time_ == null) {
              Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Time);
            break;
          }
          case 64: {
            PlaintextFOpts = input.ReadBool();
            break;
          }
          case 72: {
            PlaintextFrmPayload = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            PhyPayload = input.ReadBytes();
            break;
          }
          case 18: {
            if (txInfo_ == null) {
              TxInfo = new global::Chirpstack.Gateway.UplinkTxInfo();
            }
            input.ReadMessage(TxInfo);
            break;
          }
          case 26: {
            rxInfo_.AddEntriesFrom(ref input, _repeated_rxInfo_codec);
            break;
          }
          case 32: {
            FType = (global::Chirpstack.Common.FType) input.ReadEnum();
            break;
          }
          case 42: {
            DevAddr = input.ReadString();
            break;
          }
          case 50: {
            DevEui = input.ReadString();
            break;
          }
          case 58: {
            if (time_ == null) {
              Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Time);
            break;
          }
          case 64: {
            PlaintextFOpts = input.ReadBool();
            break;
          }
          case 72: {
            PlaintextFrmPayload = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DownlinkFrameLog : pb::IMessage<DownlinkFrameLog>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DownlinkFrameLog> _parser = new pb::MessageParser<DownlinkFrameLog>(() => new DownlinkFrameLog());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DownlinkFrameLog> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chirpstack.Stream.FrameReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DownlinkFrameLog() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DownlinkFrameLog(DownlinkFrameLog other) : this() {
      time_ = other.time_ != null ? other.time_.Clone() : null;
      phyPayload_ = other.phyPayload_;
      txInfo_ = other.txInfo_ != null ? other.txInfo_.Clone() : null;
      downlinkId_ = other.downlinkId_;
      gatewayId_ = other.gatewayId_;
      fType_ = other.fType_;
      devAddr_ = other.devAddr_;
      devEui_ = other.devEui_;
      plaintextFOpts_ = other.plaintextFOpts_;
      plaintextFrmPayload_ = other.plaintextFrmPayload_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DownlinkFrameLog Clone() {
      return new DownlinkFrameLog(this);
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp time_;
    /// <summary>
    /// Time.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "phy_payload" field.</summary>
    public const int PhyPayloadFieldNumber = 2;
    private pb::ByteString phyPayload_ = pb::ByteString.Empty;
    /// <summary>
    /// PHYPayload.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString PhyPayload {
      get { return phyPayload_; }
      set {
        phyPayload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tx_info" field.</summary>
    public const int TxInfoFieldNumber = 3;
    private global::Chirpstack.Gateway.DownlinkTxInfo txInfo_;
    /// <summary>
    /// TX meta-data.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chirpstack.Gateway.DownlinkTxInfo TxInfo {
      get { return txInfo_; }
      set {
        txInfo_ = value;
      }
    }

    /// <summary>Field number for the "downlink_id" field.</summary>
    public const int DownlinkIdFieldNumber = 4;
    private uint downlinkId_;
    /// <summary>
    /// Downlink ID.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DownlinkId {
      get { return downlinkId_; }
      set {
        downlinkId_ = value;
      }
    }

    /// <summary>Field number for the "gateway_id" field.</summary>
    public const int GatewayIdFieldNumber = 5;
    private string gatewayId_ = "";
    /// <summary>
    /// Gateway ID (EUI64).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GatewayId {
      get { return gatewayId_; }
      set {
        gatewayId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "f_type" field.</summary>
    public const int FTypeFieldNumber = 6;
    private global::Chirpstack.Common.FType fType_ = global::Chirpstack.Common.FType.JoinRequest;
    /// <summary>
    /// Frame type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chirpstack.Common.FType FType {
      get { return fType_; }
      set {
        fType_ = value;
      }
    }

    /// <summary>Field number for the "dev_addr" field.</summary>
    public const int DevAddrFieldNumber = 7;
    private string devAddr_ = "";
    /// <summary>
    /// Device address (optional).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DevAddr {
      get { return devAddr_; }
      set {
        devAddr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dev_eui" field.</summary>
    public const int DevEuiFieldNumber = 8;
    private string devEui_ = "";
    /// <summary>
    /// Device EUI (optional).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DevEui {
      get { return devEui_; }
      set {
        devEui_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "plaintext_f_opts" field.</summary>
    public const int PlaintextFOptsFieldNumber = 9;
    private bool plaintextFOpts_;
    /// <summary>
    /// Plaintext f_opts mac-commands.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool PlaintextFOpts {
      get { return plaintextFOpts_; }
      set {
        plaintextFOpts_ = value;
      }
    }

    /// <summary>Field number for the "plaintext_frm_payload" field.</summary>
    public const int PlaintextFrmPayloadFieldNumber = 10;
    private bool plaintextFrmPayload_;
    /// <summary>
    /// Plaintext frm_payload.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool PlaintextFrmPayload {
      get { return plaintextFrmPayload_; }
      set {
        plaintextFrmPayload_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DownlinkFrameLog);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DownlinkFrameLog other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Time, other.Time)) return false;
      if (PhyPayload != other.PhyPayload) return false;
      if (!object.Equals(TxInfo, other.TxInfo)) return false;
      if (DownlinkId != other.DownlinkId) return false;
      if (GatewayId != other.GatewayId) return false;
      if (FType != other.FType) return false;
      if (DevAddr != other.DevAddr) return false;
      if (DevEui != other.DevEui) return false;
      if (PlaintextFOpts != other.PlaintextFOpts) return false;
      if (PlaintextFrmPayload != other.PlaintextFrmPayload) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (time_ != null) hash ^= Time.GetHashCode();
      if (PhyPayload.Length != 0) hash ^= PhyPayload.GetHashCode();
      if (txInfo_ != null) hash ^= TxInfo.GetHashCode();
      if (DownlinkId != 0) hash ^= DownlinkId.GetHashCode();
      if (GatewayId.Length != 0) hash ^= GatewayId.GetHashCode();
      if (FType != global::Chirpstack.Common.FType.JoinRequest) hash ^= FType.GetHashCode();
      if (DevAddr.Length != 0) hash ^= DevAddr.GetHashCode();
      if (DevEui.Length != 0) hash ^= DevEui.GetHashCode();
      if (PlaintextFOpts != false) hash ^= PlaintextFOpts.GetHashCode();
      if (PlaintextFrmPayload != false) hash ^= PlaintextFrmPayload.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (time_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Time);
      }
      if (PhyPayload.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(PhyPayload);
      }
      if (txInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TxInfo);
      }
      if (DownlinkId != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(DownlinkId);
      }
      if (GatewayId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(GatewayId);
      }
      if (FType != global::Chirpstack.Common.FType.JoinRequest) {
        output.WriteRawTag(48);
        output.WriteEnum((int) FType);
      }
      if (DevAddr.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(DevAddr);
      }
      if (DevEui.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(DevEui);
      }
      if (PlaintextFOpts != false) {
        output.WriteRawTag(72);
        output.WriteBool(PlaintextFOpts);
      }
      if (PlaintextFrmPayload != false) {
        output.WriteRawTag(80);
        output.WriteBool(PlaintextFrmPayload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (time_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Time);
      }
      if (PhyPayload.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(PhyPayload);
      }
      if (txInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TxInfo);
      }
      if (DownlinkId != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(DownlinkId);
      }
      if (GatewayId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(GatewayId);
      }
      if (FType != global::Chirpstack.Common.FType.JoinRequest) {
        output.WriteRawTag(48);
        output.WriteEnum((int) FType);
      }
      if (DevAddr.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(DevAddr);
      }
      if (DevEui.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(DevEui);
      }
      if (PlaintextFOpts != false) {
        output.WriteRawTag(72);
        output.WriteBool(PlaintextFOpts);
      }
      if (PlaintextFrmPayload != false) {
        output.WriteRawTag(80);
        output.WriteBool(PlaintextFrmPayload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (time_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Time);
      }
      if (PhyPayload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(PhyPayload);
      }
      if (txInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TxInfo);
      }
      if (DownlinkId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DownlinkId);
      }
      if (GatewayId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GatewayId);
      }
      if (FType != global::Chirpstack.Common.FType.JoinRequest) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) FType);
      }
      if (DevAddr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DevAddr);
      }
      if (DevEui.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DevEui);
      }
      if (PlaintextFOpts != false) {
        size += 1 + 1;
      }
      if (PlaintextFrmPayload != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DownlinkFrameLog other) {
      if (other == null) {
        return;
      }
      if (other.time_ != null) {
        if (time_ == null) {
          Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Time.MergeFrom(other.Time);
      }
      if (other.PhyPayload.Length != 0) {
        PhyPayload = other.PhyPayload;
      }
      if (other.txInfo_ != null) {
        if (txInfo_ == null) {
          TxInfo = new global::Chirpstack.Gateway.DownlinkTxInfo();
        }
        TxInfo.MergeFrom(other.TxInfo);
      }
      if (other.DownlinkId != 0) {
        DownlinkId = other.DownlinkId;
      }
      if (other.GatewayId.Length != 0) {
        GatewayId = other.GatewayId;
      }
      if (other.FType != global::Chirpstack.Common.FType.JoinRequest) {
        FType = other.FType;
      }
      if (other.DevAddr.Length != 0) {
        DevAddr = other.DevAddr;
      }
      if (other.DevEui.Length != 0) {
        DevEui = other.DevEui;
      }
      if (other.PlaintextFOpts != false) {
        PlaintextFOpts = other.PlaintextFOpts;
      }
      if (other.PlaintextFrmPayload != false) {
        PlaintextFrmPayload = other.PlaintextFrmPayload;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (time_ == null) {
              Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Time);
            break;
          }
          case 18: {
            PhyPayload = input.ReadBytes();
            break;
          }
          case 26: {
            if (txInfo_ == null) {
              TxInfo = new global::Chirpstack.Gateway.DownlinkTxInfo();
            }
            input.ReadMessage(TxInfo);
            break;
          }
          case 32: {
            DownlinkId = input.ReadUInt32();
            break;
          }
          case 42: {
            GatewayId = input.ReadString();
            break;
          }
          case 48: {
            FType = (global::Chirpstack.Common.FType) input.ReadEnum();
            break;
          }
          case 58: {
            DevAddr = input.ReadString();
            break;
          }
          case 66: {
            DevEui = input.ReadString();
            break;
          }
          case 72: {
            PlaintextFOpts = input.ReadBool();
            break;
          }
          case 80: {
            PlaintextFrmPayload = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (time_ == null) {
              Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Time);
            break;
          }
          case 18: {
            PhyPayload = input.ReadBytes();
            break;
          }
          case 26: {
            if (txInfo_ == null) {
              TxInfo = new global::Chirpstack.Gateway.DownlinkTxInfo();
            }
            input.ReadMessage(TxInfo);
            break;
          }
          case 32: {
            DownlinkId = input.ReadUInt32();
            break;
          }
          case 42: {
            GatewayId = input.ReadString();
            break;
          }
          case 48: {
            FType = (global::Chirpstack.Common.FType) input.ReadEnum();
            break;
          }
          case 58: {
            DevAddr = input.ReadString();
            break;
          }
          case 66: {
            DevEui = input.ReadString();
            break;
          }
          case 72: {
            PlaintextFOpts = input.ReadBool();
            break;
          }
          case 80: {
            PlaintextFrmPayload = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
